# Generated by Django 3.2.9 on 2021-12-18 15:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('minelist', '0003_auto_20211207_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('point_name', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mine',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mine',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mine',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='mine',
            name='longitude',
        ),
        migrations.AddField(
            model_name='mine',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minelist.location'),
        ),
    ]
