# Generated by Django 3.2.9 on 2021-12-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minelist', '0004_auto_20211218_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ZIP / Postal code'),
        ),
    ]
